app = "psi-help24-bot"
primary_region = "ams" # Амстердам, выберите ближайший к вам регион
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  # Переменные окружения будут добавлены через командную строку

[experimental]
  auto_rollback = true